Repository Team-NBK-02/contact-app, pull requests merged in 2023-09, with the labels that each got.

#1 Base/cooperation
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/team2/contactapp/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/team2/contactapp/AddDialog.kt
  app/src/main/java/com/team2/contactapp/ContactFragment.kt
  app/src/main/java/com/team2/contactapp/DetailFragment.kt
  app/src/main/java/com/team2/contactapp/ListFragment.kt
  app/src/main/java/com/team2/contactapp/MainActivity.kt
  app/src/main/java/com/team2/contactapp/MainTabs.kt
  app/src/main/java/com/team2/contactapp/SampleData.kt
  app/src/main/java/com/team2/contactapp/User.kt
  app/src/main/java/com/team2/contactapp/ViewPagerAdapter.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_add.xml
  app/src/main/res/layout/fragment_contact.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_list.xml
  app/src/main/res/menu/menu_bottom.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/com/team2/contactapp/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: FEAT ⚙️

#9 Design/detailFragment
  app/src/main/res/drawable/call.png
  app/src/main/res/drawable/detail_gradient.xml
  app/src/main/res/drawable/detail_text_box.xml
  app/src/main/res/drawable/message.png
  app/src/main/res/layout/fragment_detail.xml
Labels: DESIGN 🎨

#8 Feature/list fragment
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/misc.xml
  DataSource.md
  app/src/main/java/com/team2/contactapp/ListFragment.kt
  app/src/main/java/com/team2/contactapp/UserRecyclerViewAdapter.kt
  app/src/main/res/drawable/fill_heart.png
  app/src/main/res/drawable/heart.png
  app/src/main/res/drawable/heart_selector.xml
  app/src/main/res/drawable/item_linear_type1_background.xml
  app/src/main/res/drawable/item_linear_type2_background.xml
  app/src/main/res/layout/fragment_list.xml
  app/src/main/res/layout/item_recyler_view_linear_type1.xml
  app/src/main/res/layout/item_recyler_view_linear_type2.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/style.xml
Labels: FEAT ⚙️, DESIGN 🎨

#12 Fix/id error
  .idea/misc.xml
  app/src/main/java/com/team2/contactapp/AddDialog.kt
  app/src/main/res/layout/dialog_add.xml
Labels: bug

#15 LittleFix/Detail Fragment
  app/src/main/res/drawable/detail_gradient.xml
  app/src/main/res/drawable/detail_text_box.xml
  app/src/main/res/drawable/pikachu.jpg
  app/src/main/res/layout/fragment_detail.xml
Labels: LITTLE_FIX 🔧

#18 [FEAT] : ⚙️ RecyclerView Swipe 구현
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/team2/contactapp/ListFragment.kt
  app/src/main/java/com/team2/contactapp/UserListItemHelper.kt
  app/src/main/java/com/team2/contactapp/UserRecyclerViewAdapter.kt
  app/src/main/res/layout/item_recyler_view_linear_type1.xml
  app/src/main/res/layout/item_recyler_view_linear_type2.xml
Labels: FEAT ⚙️

#19 Feature/listNewViewType
  app/src/main/java/com/team2/contactapp/ContactFragment.kt
  app/src/main/java/com/team2/contactapp/ListFragment.kt
  app/src/main/java/com/team2/contactapp/MainActivity.kt
  app/src/main/java/com/team2/contactapp/UserRecyclerViewAdapter.kt
  app/src/main/java/com/team2/contactapp/ViewPagerAdapter.kt
  app/src/main/res/drawable/item_grid_type1_background.xml
  app/src/main/res/drawable/item_grid_type2_background.xml
  app/src/main/res/layout/item_recyler_view_grid_type1.xml
  app/src/main/res/layout/item_recyler_view_grid_type2.xml
  app/src/main/res/menu/menu_recycler_view.xml
Labels: FEAT ⚙️

#21 Feature/detail fragment
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/team2/contactapp/DetailFragment.kt
  app/src/main/java/com/team2/contactapp/SampleData.kt
  app/src/main/res/drawable/cheolsu.png
  app/src/main/res/drawable/hoon.png
  app/src/main/res/drawable/hyeongman.png
  app/src/main/res/drawable/jjanga.png
  app/src/main/res/drawable/jjanggu.png
  app/src/main/res/drawable/maenggu.png
  app/src/main/res/drawable/miseon.png
  app/src/main/res/drawable/suji.png
  app/src/main/res/drawable/white.png
  app/src/main/res/drawable/youri.png
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/item_recyler_view_linear_type1.xml
  app/src/main/res/layout/item_recyler_view_linear_type2.xml
Labels: FEAT ⚙️

#26 Feature/like
  app/src/main/java/com/team2/contactapp/User.kt
  app/src/main/java/com/team2/contactapp/UserRecyclerViewAdapter.kt
Labels: FEAT ⚙️

#29 Merge/add dialog
  .idea/misc.xml
  .idea/vcs.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/team2/contactapp/AddDialog.kt
  app/src/main/java/com/team2/contactapp/ContactFragment.kt
  app/src/main/java/com/team2/contactapp/ListFragment.kt
  app/src/main/java/com/team2/contactapp/MainActivity.kt
  app/src/main/java/com/team2/contactapp/UserRecyclerViewAdapter.kt
  app/src/main/java/com/team2/contactapp/ViewPagerAdapter.kt
  app/src/main/res/drawable/chip_selector.xml
  app/src/main/res/layout/dialog_add.xml
  app/src/main/res/layout/fragment_list.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: FEAT ⚙️

#30 Feature/load phone book
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/team2/contactapp/ContactFragment.kt
  app/src/main/java/com/team2/contactapp/ListFragment.kt
  app/src/main/java/com/team2/contactapp/MainActivity.kt
  app/src/main/java/com/team2/contactapp/UserRecyclerViewAdapter.kt
  app/src/main/java/com/team2/contactapp/ViewPagerAdapter.kt
  app/src/main/res/layout/item_recyler_view_grid_type1.xml
  app/src/main/res/layout/item_recyler_view_grid_type2.xml
  app/src/main/res/menu/menu_recycler_view.xml
Labels: FEAT ⚙️

#34 Refactor
  app/src/main/java/com/team2/contactapp/AddDialog.kt
  app/src/main/java/com/team2/contactapp/ContactFragment.kt
  app/src/main/java/com/team2/contactapp/DetailFragment.kt
  app/src/main/java/com/team2/contactapp/ListFragment.kt
  app/src/main/java/com/team2/contactapp/MainActivity.kt
  app/src/main/java/com/team2/contactapp/SampleData.kt
  app/src/main/java/com/team2/contactapp/User.kt
  app/src/main/java/com/team2/contactapp/UserListItemHelper.kt
  app/src/main/java/com/team2/contactapp/UserRecyclerViewAdapter.kt
  app/src/main/java/com/team2/contactapp/Util.kt
  app/src/main/res/layout/fragment_detail.xml
Labels: REFACTOR ♻️
